#!/bin/sh

#
# skrypt zatrzymujący dysk twardy
# @j00zek
# wersja 2014-12-16
# To MUSI byc ostatni skrypt, aby dysk sie nie wzbudzil

. /etc/sysconfig/gfunctions #wczytanie funkcji wspólnych dla skryptów Graterlia
GOSdebug ">>>>>>>>>> $0"

bootDEV=`sed "s;^.*root=/dev/\(sd[abcdef]\).*$;\1;" </proc/cmdline`
if echo $bootDEV | grep -q sd; then
	if [ `cat /sys/block/$bootDEV/removable` -eq 0 ]; then #tylko dla startu z dysku
		if [ ! -f /tmp/.sdparm ]; then
			cp -f /usr/bin/sdparm /tmp/.sdparm
		fi
		if ! mount | grep -lq sdparm; then
			mount --bind /tmp/.sdparm /usr/bin/sdparm # to teraz sdparm bedzie uruchamiany z tmp ;)
		fi
	fi
fi

doSPINDOWN()
{
#czekamy na zakonczenie procesu uruchamiania moderate
WaitingTime=10
while [ "$WaitingTime" -gt 0 ]
do
	sleep 1
	[ -f /var/etc/moderate_standby ] && WaitingTime=0 || WaitingTime=$(( $WaitingTime - 1 ))
done
sync
sleep 1
#usypiamy dyski
for myHDD in `grep 'sd.$' </proc/partitions | awk '{print $4}'`
do
	if [ `cat /sys/block/$myHDD/removable` -eq 0 ]; then #tylko dyski
		#sdparm --set=SCT=10 /dev/$myHDD
		GOSdebug "Syncing /dev/$myHDD"
		sdparm --flexible --command=sync /dev/$myHDD
		GOSdebug "Spindown /dev/$myHDD"
		sleep 1
		sdparm --flexible --readonly --command=stop /dev/$myHDD
	fi
done
}

echo "               " >/dev/vfd
sync

if `grep 'sd.$' </proc/partitions | grep -q '[0-9]\{8\}'`;then #tylko wieksze od 10000000 blokow, czyli pomijamy
	doSPINDOWN &
fi
