#!/bin/sh

# Graterlia OS
# homepage: http://graterlia.xunil.pl
# e-mail: nbox@xunil.pl
#
# skrypt synchronizujący czas z ntp
# wersja 2014-12-21

. /etc/sysconfig/gfunctions #wczytanie funkcji wsplnych dla skryptw Graterlia
. /var/grun/grcstype #załadowanie informacji o rodzaju odbiornika
. /var/grun/gfronttype #załadowanie zmiennej vfd
. /etc/ntpd.conf
PATH=/sbin:/bin:/usr/sbin:/usr/bin #deklaracja ścieżek

ping -q -c1 212.77.100.101
if [ $? -eq 0 ]; then # ping zwroci kod bledu, jak sie nie uda :)
	(/usr/sbin/ntpdate $NTPOPTIONS $NTPSERVERS >/dev/null) &
fi
